let projectInfo = [
  {
    id: 1,
    title: "Ema John",
    technology: ["CSS", "React", "MongoDB"],
    img: "https://i.ibb.co/5FcWxXk/ema-john.png",
    description:
      "Ema John is a e-commerce development service website where a customer can order for a web site design, mobile app development, andriod and ios app development.Web development is the work involved in developing a Web site for the Internet or an intranet. Web development can range from developing a simple single static page of plain text to complex Web-based Internet applications, electronic businesses, and social network services.",
    features: [
      "A bunch list of products ","Add product to cart ","total prices with tax ","collect shipment information ","online payment gateway ","log in info",
    ],
    feature1:"A bunch list of products ",
    feature2:"Add product to cart",
    feature3:"total prices with tax",
    feature4:"collect shipment information ",
    feature5:"online payment gateway ",
    feature6:"login info",
    liveSite: "https://ema-john.firebaseapp.com/",
    github: "https://github.com/sharif-hossain/ema-john-shopping",
    image1: "https://i.ibb.co/5FcWxXk/ema-john.png",
    image2:"https://i.ibb.co/r6LyjrK/ema.png",
  },
  {
    id: 2,
    title: "Creative Agency",
    technology: ["Bootstrap", "React", "Node.js"],
    img: "https://i.ibb.co/fk78Lws/creative.png",
    description:
      "Creative agency is a e-commerce development service website where a customer can order for a web site design, mobile app development, andriod and ios app development.Web development is the work involved in developing a Web site for the Internet or an intranet. Web development can range from developing a simple single static page of plain text to complex Web-based Internet applications, electronic businesses, and social network services.",
    features: [
      "Order for a creative design ","Can upload image for detail information ","Give a review or feedback ","Add a service ","Check all ordered service ","Delete a service ",
    ],
    feature1:"Order for a creative design  ",
    feature2:"Can upload image for detail information",
    feature3:"Give a review or feedback ",
    feature4:"Add a service ",
    feature5:"Check all ordered service",
    feature6:"Delete a service ",
    liveSite: "https://creativeagencyrecap.web.app//",
    github: "https://github.com/sharif-hossain/creative-agency-client",
    image1: "https://i.ibb.co/fk78Lws/creative.png",
  },
  {
    id: 3,
    title: "Volunteer Network",
    technology: ["Sass", "Redux", "React"],
    img: "https://i.ibb.co/wWP1b0w/volunteer.png",
    description:
      "Volunteer network is a e-commerce development service website where a customer can order for a web site design, mobile app development, andriod and ios app development.Web development is the work involved in developing a Web site for the Internet or an intranet. Web development can range from developing a simple single static page of plain text to complex Web-based Internet applications, electronic businesses, and social network services.",
    features: [
      "Add volunteer option ","Register as a volunteer ", "Delete registered option ","Show all volunteer list ", "Delete volunteer by admin ", "Add volunteer details ",
    ],
    feature1:"Add volunteer option ",
    feature2:"Register as a volunteer ",
    feature3:"Delete registered option ",
    feature4:"Show all volunteer list",
    feature5:"Delete volunteer by admin ",
    feature6:"Add volunteer details ",

    liveSite: "https://volunteer-working.web.app/",
    // github: [
    //   "https://github.com/sharif-hossain/creative-agency-client",
    //   // "https://github.com/sharif-hossain/creative-agency-server",
    // ],
    github: "https://github.com/sharif-hossain/volunteer-network-client",
    ui: [
      "https://i.ibb.co/RpBWp3K/2-login.png",
      "https://i.ibb.co/HDt5Zyx/3-Customar-place-Order.png",

      "https://i.ibb.co/RyHxbXv/4-Customar-status.png",
      "https://i.ibb.co/Ttbzj43/5-Customar-review.png",
      "https://i.ibb.co/FHR6Px5/6-Admin-service-status.png",
      "https://i.ibb.co/YTBty8r/7-Admin-add-service.png",
      "https://i.ibb.co/N7657nV/8-Admin-make-admin.png",
    ],
    image1: "https://i.ibb.co/wWP1b0w/volunteer.png",
	image2: "https://i.ibb.co/RyHxbXv/4-Customar-status.png",
      image3: "https://i.ibb.co/Ttbzj43/5-Customar-review.png",
  },
  {
    id: 4,
    title: "Travel Resort",
    technology: ["React", "Express", "MongoDB"],
    img: "https://i.ibb.co/H4M9fwS/travel.png",
    description:
      "Travel resort is a e-commerce development service website where a customer can order for a web site design, mobile app development, andriod and ios app development.Web development is the work involved in developing a Web site for the Internet or an intranet. Web development can range from developing a simple single static page of plain text to complex Web-based Internet applications, electronic businesses, and social network services.",
    features: [
      "Traveller can choose a resort ",
      "Hotel booking with date ",
      "google map ",
      "Traveller can choose a resort ",
      "Hotel booking with date ",
      "google map ",
    ],
    feature1:"Traveller can choose a resort ",
    feature2:"Hotel booking with date ",
    feature3:"google map",
    feature4:"Add resort option",
    feature5:"login details",
    feature6:"Show all booking ",
    liveSite: "https://travel-resort-09.netlify.app/",
    github: "https://github.com/sharif-hossain/travel-resort",
    image1: "https://i.ibb.co/H4M9fwS/travel.png",
  },
  {
    id: 5,
    title: "Doctors Portal",
    technology: ["Bootstrap", "React", "MongoDB"],
    img: "https://i.ibb.co/H4s0ZKZ/doctor.png",
    description:
      "Doctors portal is a e-commerce development service website where a customer can order for a web site design, mobile app development, andriod and ios app development.Web development is the work involved in developing a Web site for the Internet or an intranet. Web development can range from developing a simple single static page of plain text to complex Web-based Internet applications, electronic businesses, and social network services.",
    features: [
      "Patient can book a doctor ",
      "Book a doctor with specified date ",
      "Admin can add doctor services ",
      "Admin can see all patient list",
      "PAtient can book a doctor ",
      "Book a doctor with specified date ",
    ],
    feature1:"Patient can book a doctor ",
    feature2:"Book a doctor with specified date ",
    feature3:"Admin can add doctor services ",
    feature4:"Admin can see all patient list",
    feature5:"PAtient can book a doctor ",
    feature6:"Book a doctor with specified date ",
    liveSite: "https://doctors-portal-ph.web.app/",
    github: "https://github.com/sharif-hossain/doctors-portal-client",
    image1: "https://i.ibb.co/H4s0ZKZ/doctor.png",
  },
  {
    id: 6,
    title: "Burj Al Arab",
    technology: ["CSS", "HTML5", "React"],
    img: "https://i.ibb.co/SvrMx5z/burjalarab.png",
    description:
      "The Burj Al Arab (Tower of the Arabs) is a luxury hotel located in the city of Dubai, One can book in a room for a particular date for a reasonable price, Room can be single double and family. In family room pet can be allowed",
    features: [
      "Customer can book a room",
      "Online payment",
      "delete a book",
      "Admin can add a book",
      "Pricing system",
      "delete a book",
    ],
    feature1:"Customer can book a room",
    feature2:"Online payment",
    feature3:"delete a book",
    feature4:"Admin can add a book",
    feature5:"Pricing system",
    feature6:"delete a book",
    // liveSite: "https://travel-resort-09.netlify.app/",
     github: "https://github.com/sharif-hossain/burj-al-arab",
    image1: "https://i.ibb.co/SvrMx5z/burjalarab.png",
  },
];
export default projectInfo;
